version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=development
      - APP_PORT=8081
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=onlinestore
      - DB_PASSWORD=postgres
      - DB_SSL_MODE=disable
      - JWT_SECRET=qwertadrianfahriaffandi29042003
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlinestore
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    volumes:
      - ./database/migrations:/migrations
    command: [
      "-path", "/migrations/", 
      "-database", "postgres://postgres:postgres@db:5432/onlinestore?sslmode=disable", 
      "up"
    ]

networks:
  default:
    driver: bridge
